## First time calling "./run_kubernetes.sh"

pod/mypod created
NAME    READY   STATUS              RESTARTS   AGE
mypod   0/1     ContainerCreating   0          1s
error: unable to forward port because pod is not running. Current status=Pending



## Second time calling "./run_kubernetes.sh"
## "Handing connection" line appears after calling "./make_prediction.sh"

Error from server (AlreadyExists): pods "mypod" already exists
NAME    READY   STATUS    RESTARTS   AGE
mypod   1/1     Running   0          2m43s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000


## Running "kubectl logs mypod" shows the output of running make_predictions.sh when cluster is up

* Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 121-253-204
[2022-09-10 19:25:16,658] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-09-10 19:25:16,670] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-09-10 19:25:16,680] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-09-10 19:25:16,683] INFO in app: Output prediction: [20.35373177134412]
127.0.0.1 - - [10/Sep/2022 19:25:16] "POST /predict HTTP/1.1" 200 -
